In [9]:
import random
import numpy as np

In [2]:
a = []

In [3]:
for i in range(1000000):
    a.append(random.random())

In [4]:
len(a)

1000000

In [10]:
stock_change = np.random.normal(0, 1, (8, 10))

In [11]:
a = np.array([[80, 86],
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])
b = np.array([[0.7], [0.3]])

np.mat(a)

matrix([[80, 86],
        [82, 80],
        [85, 78],
        [90, 90],
        [86, 82],
        [82, 90],
        [78, 80],
        [92, 94]])

In [12]:
b = np.array([[0.3],[0.7]])

In [13]:
np.dot(a,b)

array([[84.2],
       [80.6],
       [80.1],
       [90. ],
       [83.2],
       [87.6],
       [79.4],
       [93.4]])

In [14]:
mat_a = np.mat(a)
mat_b = np.mat(b)

In [15]:
mat_a * mat_b

matrix([[84.2],
        [80.6],
        [80.1],
        [90. ],
        [83.2],
        [87.6],
        [79.4],
        [93.4]])

In [16]:
np.matmul(a,b)

array([[84.2],
       [80.6],
       [80.1],
       [90. ],
       [83.2],
       [87.6],
       [79.4],
       [93.4]])